version: '3.2'
services:
 iam-service:
  image: quay.io/keycloak/keycloak:22.0.1
  container_name: iam-service
  restart: always
  ports:
   - 9098:8080
   - 9099:8443
  environment:
   KC_FEATURES: admin-api,authorization,client-policies,docker,dynamic-scopes,impersonation,token-exchange,scripts,web-authn
  #KC_HOSTNAME: iam-service
   KC_HOSTNAME_STRICT: 'false'
   KC_HTTPS_CLIENT_AUTH: request
   KC_HTTPS_PORT: 8443
   KC_HTTPS_PROTOCOLS: TLSv1.3,TLSv1.2
   KC_HTTP_ENABLE: 'true'
   KC_HTTP_PORT: 8080
   KC_METRICS_ENABLED: 'true'
   KC_PROXY: edge
   KEYCLOAK_ADMIN: admin
   KEYCLOAK_ADMIN_PASSWORD: password
   PROXY_ADDRES_FORWARDING: 'true'   
   KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/https_keys/localhostcrt.pem
   KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/https_keys/localhostkey.pem
  entrypoint: /opt/keycloak/bin/kc.sh start --optimized
  volumes:
   - ./https_keys:/opt/keycloak/https_keys 
  
 
