version: '3.2'
networks:
  iam-network:
   driver: bridge

services:
 iam-service:
  image: quay.io/keycloak/keycloak:22.0.1
  container_name: iam-service
  restart: always
  ports:
   - 9098:8080
   - 9099:8443
  environment:
   KC_FEATURES: admin-api,authorization,client-policies,docker,dynamic-scopes,impersonation,token-exchange,scripts,web-authn
   KC_HOSTNAME_STRICT: 'false'  
   KC_HTTPS_PORT: 8443   
   KC_HTTP_PORT: 8080
   KC_METRICS_ENABLED: 'true'  
   KEYCLOAK_ADMIN: admin
   KEYCLOAK_ADMIN_PASSWORD: password   
   KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/iam-files/certes/crt.pem
   KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/iam-files/certes/key.pem
  entrypoint: /opt/keycloak/bin/kc.sh start --optimized
  volumes:
   - ./iam-files/certes:/opt/keycloak/iam-files/certes
  networks:
   - iam-network 
  
 
